### ISSUE TITLE
[bug-report] Provider signIn button doesn`t redirect to privider if configured as "Big Icon"

### ISSUE THREAD

**Issue by keisni** [casdoor/casdoor#2875] opened 2024-04-16 11:20 UTC
Steps to reproduce:
1. Add a custom OAuth provider.
2. Add a application which use the provider in step 1.
3. In application`s Signin items list, select "Big Icon" as Provider`s Rule.
4. I used go sdk to redirect user to the application`s sinIn page.
5. Some user click Oauth provider`s "Big Icon"
6. The  user got error "Please input your Email or Phone!" noticed in red color.

Expected:
The user can be redirected to the provider`s login plage.

Version:
v1.585.0

**Comment by hsluoyz** [comment] 2024-04-20 01:14
@keisni cannot reproduce this. Give more screenshots and demo videos

**Comment by keisni** [comment] 2024-04-22 05:44
https://github.com/casdoor/casdoor/assets/4084002/c9817bf4-864c-44af-b877-b7a63ed329f9
SSO is the "name" of custom oauth provider.

**Comment by hsluoyz** [comment] 2024-04-22 11:46
@keisni can you reproduce it in demo site: https://demo.casdoor.com/ ? What is your application setting? Can you post the full JSON of the application?

**Comment by keisni** [comment] 2024-04-23 01:48
@hsluoyz may I ask you that how can i export JSON of my application and provider?

**Comment by hsluoyz** [comment] 2024-04-23 05:06
@keisni get the response of the API request (via Chrome F12)

**Comment by keisni** [comment] 2024-04-23 11:49
![big](https://github.com/casdoor/casdoor/assets/4084002/06cb7aba-0fca-4d03-bedd-4faa6d8c571a)
I`m afraid that I cant upload the full app json coz it contains censtive information, and it`s just a simple app with custom oauth provider.

**Comment by hsluoyz** [comment] 2024-04-23 14:11
@keisni it can't be reproduced in: https://door.casdoor.com/login/oauth/authorize?client_id=0ba528121ea87b3eb54d&response_type=code&redirect_uri=https%3A%2F%2Fforum.casbin.com%2Fcallback&scope=read&state=app-casbin-oa

(please ignore the final error like below)

![image](https://github.com/casdoor/casdoor/assets/3787410/43b93447-1f0e-413e-bd33-d60fc9dbbff9)

**Comment by keisni** [comment] 2024-04-24 02:36
@halozhy can you show me a example app with provicer { "type": "Custom", "category": "OAuth" } showed with big icon?

**Comment by hsluoyz** [comment] 2024-04-26 15:36
Fixed by: https://github.com/casdoor/casdoor/pull/2900

**Closed** 2024-04-26 15:36 UTC
Labels: bug
