### ISSUE TITLE
docker-compose beego error

### ISSUE THREAD

**Issue by stefanwuthrich** [casdoor/casdoor#1444] opened 2023-01-03 11:45 UTC
I try to run casdoor with Makefile and tried also with docker-compose and get always same error:

casdoor-casdoor-1 exited with code 2
casdoor-casdoor-1  | panic: prefix should has path
casdoor-casdoor-1  | 
casdoor-casdoor-1  | goroutine 1 [running]:
casdoor-casdoor-1  | github.com/beego/beego.(*Tree).addtree(0x0, {0x2b42ae0, 0x174ef40, 0xc000a0e4e8}, 0x1, {0x0, 0x0, 0xc000a0e018}, {0x0, 0x0})
casdoor-casdoor-1  | 	/go/src/casdoor/vendor/github.com/beego/beego/tree.go:58 +0x1185
casdoor-casdoor-1  | github.com/beego/beego.(*Tree).AddTree(0x174ef40, {0x0, 0xc000040430}, 0x3)
casdoor-casdoor-1  | 	/go/src/casdoor/vendor/github.com/beego/beego/tree.go:53 +0x54
casdoor-casdoor-1  | github.com/beego/beego.(*Namespace).Namespace(0xc0000ae828, {0xc00035b278, 0x1, 0x1})
casdoor-casdoor-1  | 	/go/src/casdoor/vendor/github.com/beego/beego/namespace.go:212 +0x205
casdoor-casdoor-1  | github.com/beego/beego.NSNamespace.func1(0x30)
casdoor-casdoor-1  | 	/go/src/casdoor/vendor/github.com/beego/beego/namespace.go:387 +0x5a
casdoor-casdoor-1  | github.com/beego/beego.NewNamespace({0x19eb591, 0x1}, {0xc00035bce0, 0x2, 0x1})
casdoor-casdoor-1  | 	/go/src/casdoor/vendor/github.com/beego/beego/namespace.go:42 +0x104
casdoor-casdoor-1  | github.com/casdoor/casdoor/routers.initAPI()
casdoor-casdoor-1  | 	/go/src/casdoor/routers/router.go:33 +0x1a7
casdoor-casdoor-1  | github.com/casdoor/casdoor/routers.init.1()
casdoor-casdoor-1  | 	/go/src/casdoor/routers/router.go:29 +0x17

**Comment by stefanwuthrich** [comment] 2023-01-03 19:04
Sure. I already did this, but will give it a try on another machine later

**Comment by stefanwuthrich** [comment] 2023-01-04 06:09
I tried a clean start, and the same result. Linux, Go 1.18.1

❯ go mod tidy
❯ go run main.go
2023/01/04 03:05:26.440 [I] [parser.go:111]  generate router from comments
2023/01/04 03:05:26.442 [I] [router.go:288]  /home/stefan/go/src/github.com/casdoor/casdoor/controllers no changed
panic: Error 1049: Unknown database 'casdoor'

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Adapter).createTable(0xc000157ec0)
	/home/stefan/go/src/github.com/casdoor/casdoor/object/adapter.go:128 +0x8ae
github.com/casdoor/casdoor/object.InitAdapter(0x0)
	/home/stefan/go/src/github.com/casdoor/casdoor/object/adapter.go:53 +0xb1
main.main()
	/home/stefan/go/src/github.com/casdoor/casdoor/main.go:38 +0xa6
exit status 2
❯ nano conf/app.conf
❯ go run main.go
2023/01/04 03:06:52.275 [I] [router.go:288]  /home/stefan/go/src/github.com/casdoor/casdoor/controllers no changed
2023/01/04 03:06:52.276 [I] [router.go:288]  /home/stefan/go/src/github.com/casdoor/casdoor/controllers no changed
panic: prefix should has path

goroutine 1 [running]:
github.com/beego/beego.(*Tree).addtree(0xc0001500f0?, {0x2a27d68?, 0x0?, 0xc0008089c8?}, 0xc000802ab0?, {0x0?, 0x0?, 0xc000808018?}, {0x0, 0x0})
	/home/stefan/go/pkg/mod/github.com/beego/beego@v1.12.11/tree.go:58 +0x1218
github.com/beego/beego.(*Tree).AddTree(0x174a800?, {0x0?, 0xc000048184?}, 0x3?)
	/home/stefan/go/pkg/mod/github.com/beego/beego@v1.12.11/tree.go:53 +0x54
github.com/beego/beego.(*Namespace).Namespace(0xc000126408, {0xc0002a5288, 0x1, 0x1?})
	/home/stefan/go/pkg/mod/github.com/beego/beego@v1.12.11/namespace.go:212 +0x205
github.com/beego/beego.NSNamespace.func1(0x30?)
	/home/stefan/go/pkg/mod/github.com/beego/beego@v1.12.11/namespace.go:387 +0x5a
github.com/beego/beego.NewNamespace({0x19eb092, 0x1}, {0xc0002a5cf0, 0x2, 0x1?})
	/home/stefan/go/pkg/mod/github.com/beego/beego@v1.12.11/namespace.go:42 +0x104
github.com/casdoor/casdoor/routers.initAPI()
	/home/stefan/go/src/github.com/casdoor/casdoor/routers/router.go:33 +0x1ac
github.com/casdoor/casdoor/routers.init.1()
	/home/stefan/go/src/github.com/casdoor/casdoor/routers/router.go:29 +0x17
exit status 2

my app.conf

appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = postgres
dataSourceName = "user=postgres password=*** host=172.25.0.2 port=5555 sslmode=disable dbname=casdoor"
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint = 172.25.0.2:6379
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
ldapServerPort = 389
languages = en,zh,es,fr,de,ja,ko,ru
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}

**Comment by stefanwuthrich** [comment] 2023-01-04 15:29
Manjaro Linux latest (rolling), Go 1.18.1, postgresql:15.1.0, yarn v1.22.19, v16.16.0

**Comment by hsluoyz** [comment] 2023-01-06 01:17
@stefanwuthrich I think this is a bug between Beego and Manjaro Linux. See: https://github.com/beego/beego/issues/5047 and https://github.com/beego/beego/issues/5134 . Do you have any chance to use other Linux distributions other than Manjaro Linux like Ubuntu or CentOS?

**Comment by stefanwuthrich** [comment] 2023-01-08 17:47
don't know if that helps, but I tried to debug and got to following
in router.go, the initAPI() we have:
```

ns := beego.NewNamespace("/",
		beego.NSNamespace("/api",
			beego.NSInclude(
				&controllers.ApiController{},
			),
		),
		beego.NSNamespace("",
			beego.NSInclude(
				&controllers.RootController{},
			),
		),
	)
	beego.AddNamespace(ns)

```
at last line I get into error I posted (missing prefix)
when I put a prefix with a value for both, like here:
```

ns := beego.NewNamespace("/1",
		beego.NSNamespace("/api",
			beego.NSInclude(
				&controllers.ApiController{},
			),
		),
		beego.NSNamespace("/2",
			beego.NSInclude(
				&controllers.RootController{},
			),
		),
	)
	beego.AddNamespace(ns)

```
the fatal error does not happen and the server starts (obviously not with the correct path etc, but without the posted error

**Comment by OutOfEastGate** [comment] 2023-01-11 13:51
@stefanwuthrich This should be a problem with database initialization. I found that PostgreSql has problems creating databases. You can choose to use MySQL or manually create a database called casdoor in PostgreSql. I am looking for the cause of the database initialization failure

**Comment by OutOfEastGate** [comment] 2023-01-13 08:43
@stefanwuthrich Hi,I used Manjaro Linux, Go 1.18.1,yarn v1.22.19 to run casdoor, but the error you mentioned did not occur. docker-compose and main.go are run without errors.

This is my linux version：6.1.1-1-MANJARO

This is the result
![image](https://user-images.githubusercontent.com/101807499/212275872-5439d70c-951b-474a-a54a-9cf01c168108.png)

I don't know whether it is because of the linux model. Could you please provide your specific linux model?

**Comment by stefanwuthrich** [comment] 2023-01-14 06:38
Linux version 5.15.85-1-MANJARO (builduser@fv-az334-233) (gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.39.0) #1 SMP PREEMPT Wed Dec 21 21:15:06 UTC 2022

**Comment by xiao-niu-ren** [comment] 2023-01-14 19:21
I also used Manjaro Linux(Release:22.0.0, [latest version](https://hub.docker.com/layers/manjarolinux/base/latest/images/sha256-d9a6df0240e660dd485194ea885b3483dd3d4f631910a26efc11590a9faa1545?context=explore)), Go 1.18.1, yarn v1.22.19, node 16.0.0 to run casdoor. It also works fine on my machine.
<img width="613" alt="image" src="https://user-images.githubusercontent.com/84443886/212492172-9e78b240-3e78-4299-b8eb-43ea3cf65ff0.png">

**Comment by hsluoyz** [comment] 2023-01-15 01:29
@stefanwuthrich it seems that it's very hard for us to setup an environment and reproduce your issue, can you provide a Docker script that will reproduce your issue directly based on the Manjaro base image? https://hub.docker.com/r/manjarolinux/base/tags

**Comment by OutOfEastGate** [comment] 2023-01-15 12:29
> Linux version 5.15.85-1-MANJARO (builduser@fv-az334-233) (gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.39.0) #1 SMP PREEMPT Wed Dec 21 21:15:06 UTC 2022

![img](https://user-images.githubusercontent.com/101807499/212539070-76c8ec4b-3d47-4d3d-bf98-89bda526af4a.png)
I used the version of linux system you provided, but it still has no problems. You can try pulling in casdoor's code directly and run docker-compose without making any changes. If it works , maybe there is something wrong with your casdoor configuration.

Hope this helps you.

**Comment by hsluoyz** [comment] 2023-01-21 02:01
Closed as resolved

**Closed by hsluoyz** 2023-01-21 02:01 UTC
Labels: bug
