### ISSUE TITLE
Cannot build with go  version 1.17 anymore

### ISSUE THREAD

**Issue by pangz-lab** [casdoor/casdoor#3149] opened 2024-08-29 03:36 UTC
Building using <b>go</b> [`v1.17+`](https://casdoor.org/docs/basic/server-installation/) for Production doesn't work anymore as new features added require at least version `1.20+` to work.
![image](https://github.com/user-attachments/assets/a4edfea9-58ff-4b73-b10f-a4749f37d9fe)
![image](https://github.com/user-attachments/assets/dae60814-9827-4f6a-8dbc-9ac5001fad50)

Building using version v1.20+ though generates an error due to `-buildvcs` which is known <b>go</b> [issue](https://github.com/golang/go/issues/49004) <b>(NOT CASDOOR</b>).
![image](https://github.com/user-attachments/assets/b643e52a-8d67-411c-b3e7-451bc038ec92)

The workaround is to build it with the `buildvcs` flag disable added in the build command like the following.
```
go build -buildvcs=false .
```
Building this way should work smoothly.

**Comment by dacongda** [comment] 2024-08-30 13:59
I'm sorry that I can;'t reproduce this issue when I use go1.23.0 linux/amd64
![image](https://github.com/user-attachments/assets/adb351b8-f321-477e-a414-1a0189b0a736)

and according to the issue you provide, it seems that you are using different vcs tool in the parent directory that cause build fail

**Comment by hsluoyz** [comment] 2024-08-30 14:02
Closed as cannot reproduce

**Closed by hsluoyz** 2024-08-30 14:02 UTC
Labels: question
