### ISSUE TITLE
casdoor deploied in k8s, login status code is 403

### ISSUE THREAD

**Issue by ivanmissu** [casdoor/casdoor#1273] opened 2022-11-08 04:23 UTC
casdoor deploied in k8s, and access is ok, but when i login,  http status code showed 403.\
the casdoor docker image is casbin/casdoor:v1.152.0
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/8721615/200474617-8b4dd933-5ab9-49d0-beff-a05cdd5843dc.png">
how to resolve this ?

**Comment by Abingcbc** [comment] 2022-11-08 06:55
@ivanmissu Could you provide your yaml?

**Comment by ivanmissu** [comment] 2022-11-08 07:10
@Abingcbc 

apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: casdoor-svc
  labels:
    app: casdoor
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: casdoor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: casdoor-deployment
  labels:
    app: casdoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor-container
          image: casbin/casdoor:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /conf/app.conf
              name: conf
              subPath: app.conf
            - mountPath: /init_data.json
              name: conf
              subPath: init-data.json
          env:       
            - name: RUNNING_IN_DOCKER
              value: "true"
      volumes:
        - name: conf
          configMap:
            name: casdoor-config

**Comment by ivanmissu** [comment] 2022-11-08 07:12
[k8syaml.txt](https://github.com/casdoor/casdoor/files/9958604/k8syaml.txt)
@Abingcbc

**Comment by Abingcbc** [comment] 2022-11-08 12:42
@ivanmissu I have try your yaml and there is no problem with casdoor image.

It looks like you are using `https`. How do you access Casdoor? It works well when I access casdoor through `NodePort`. Maybe it is caused by the way you export casdoor service and TLS certificate

**Comment by ivanmissu** [comment] 2022-11-08 13:32
> 

i use ClusterIP in pod,  use nginx-ingress(https) proxy to pod, other app is ok, i will try nodeport

**Comment by ivanmissu** [comment] 2022-11-09 09:35
@Abingcbc i tried to use http, it also 403
![image](https://user-images.githubusercontent.com/8721615/200794258-41deafb6-97ed-4723-b0ff-886621ae87a2.png)

**Comment by Abingcbc** [comment] 2022-11-09 13:44
@ivanmissu Could you provide your `app.conf`?

**Comment by Abingcbc** [comment] 2022-11-09 13:55
The only possible reason is that the request is forbidden by CORS filter
https://github.com/casdoor/casdoor/blob/f818200c95a7f87478858b388b59a717a328d81e/routers/cors_filter.go#L33-L50
@ivanmissu Could you provide your `app.conf`? Or check if Casdoor print any log by `kubectl logs <pod name>`?

**Comment by ivanmissu** [comment] 2022-11-10 01:15
@Abingcbc i know it ,  the origin is not modified in my configuration file.    I can login normally after configuration，  thaks.

**Comment by hsluoyz** [comment] 2022-11-10 01:57
@ivanmissu close the issue if resolved

**Closed** 2022-11-10 12:51 UTC
Labels: bug
