### ISSUE TITLE
Helm install failed, unknown driver "sqlite3"

### ISSUE THREAD

**Issue by ybizeul** [casdoor/casdoor#3223] opened 2024-09-21 13:16 UTC
```
panic: sql: unknown driver "sqlite3" (forgotten import?)

goroutine 1 [running]:
github.com/casdoor/casdoor/object.InitAdapter()
    /go/src/casdoor/object/ormer.go:98 +0x23b
main.main()
    /go/src/casdoor/main.go:35 +0x30
```

**Comment by ZhaoYP-2001** [comment] 2024-09-23 06:30
@ybizeul I can't reproduce your error. Can you provide specific reproduction steps/command execution screenshots?
![helm](https://github.com/user-attachments/assets/964c9d0f-660f-45e8-9522-c30e0140eb58)

**Comment by hsluoyz** [comment] 2024-09-23 07:54
Closed as cannot reproduced

**Closed by hsluoyz** 2024-09-23 07:54 UTC
Labels: bug

**Comment by ybizeul** [comment] 2024-09-23 08:40
So the driver name in the chart `sqlite3` is normal, and shouldn't be `sqlite` ?
