### ISSUE TITLE
Users synced from openldap-server to casdoor cannot be edited

### ISSUE THREAD

**Issue by aosolao** [casdoor/casdoor#2189] opened 2023-08-08 08:55 UTC
![Snipaste_2023-08-08_16-43-15](https://github.com/casdoor/casdoor/assets/30789071/91086c01-2f21-429e-aa59-bed94007cf7e)
![Snipaste_2023-08-08_16-43-06](https://github.com/casdoor/casdoor/assets/30789071/9643daf8-1942-499a-baab-0d31470d55f0)

After syncing users from openldap-server to casdoor, clicking the "Edit" button results in a blank page, as shown in the image above.

casdoor version: v1.379.0

**Comment by aosolao** [comment] 2023-08-08 09:05
This seems to be because casdoor did not configure the "apps" from the organization for the users during syncing.

If the default apps are manually added for the users in the database, then it becomes possible to edit the users.

**Comment by hsluoyz** [comment] 2023-08-08 09:08
@aosolao you mean the "Default application" field? What are the values for this field of your users imported via LDAP?

**Comment by aosolao** [comment] 2023-08-08 09:51
![image](https://github.com/casdoor/casdoor/assets/30789071/89866b21-2bb0-4baf-a26a-3ffe254ca99c)
![image](https://github.com/casdoor/casdoor/assets/30789071/8114969e-a838-49a9-b1d4-6ad01984a189)
Yes, the value is empty for users imported from ldap.

**Comment by hsluoyz** [comment] 2023-08-08 13:59
@aosolao fixed by: https://github.com/casdoor/casdoor/commit/62b2082e8234ec5f407ae907b50408a6ea6228fd

**Closed by hsluoyz** 2023-08-08 13:59 UTC
Labels: enhancement

**Comment by aosolao** [comment] 2023-08-11 07:07
I'm experiencing new errors after upgrading to the recently released version v1.385.0.

```
[xorm] [warn]  2023/08/11 07:03:31.342839 Table provider has column custom_scope but struct has not related field
[xorm] [warn]  2023/08/11 07:03:31.391273 Table payment has column organization but struct has not related field
panic: the adapter: built-in/api-adapter-built-in for enforcer: built-in/api-enforcer-built-in is not found

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
	/go/src/casdoor/authz/authz.go:38 +0x153
main.main()
	/go/src/casdoor/main.go:51 +0xaa
```

@hsluoyz

**Comment by hsluoyz** [comment] 2023-08-11 08:25
@aosolao delete three DB tables: `model`, `adapter` and `enforcer`, restart Casdoor

**Comment by aosolao** [comment] 2023-08-11 09:15
> @aosolao delete three DB tables: `model`, `adapter` and `enforcer`, restart Casdoor


A new error
```
[xorm] [warn]  2023/08/11 09:14:37.581033 Table provider has column custom_scope but struct has not related field
[xorm] [warn]  2023/08/11 09:14:37.635839 Table payment has column organization but struct has not related field
panic: Error 1146: Table 'casdoor.casbin_api_rule' doesn't exist

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
	/go/src/casdoor/authz/authz.go:111 +0x13f
main.main()
	/go/src/casdoor/main.go:51 +0xaa
```
@hsluoyz

**Comment by leo220yuyaodog** [comment] 2023-08-11 09:47
> > @aosolao delete three DB tables: `model`, `adapter` and `enforcer`, restart Casdoor
> 
> A new error
> 
> ```
> [xorm] [warn]  2023/08/11 09:14:37.581033 Table provider has column custom_scope but struct has not related field
> [xorm] [warn]  2023/08/11 09:14:37.635839 Table payment has column organization but struct has not related field
> panic: Error 1146: Table 'casdoor.casbin_api_rule' doesn't exist
> 
> goroutine 1 [running]:
> github.com/casdoor/casdoor/authz.InitApi()
> 	/go/src/casdoor/authz/authz.go:111 +0x13f
> main.main()
> 	/go/src/casdoor/main.go:51 +0xaa
> ```
> 
> @hsluoyz

What database you are using? The table will be created auto when Casdoor uses mysql.

**Comment by aosolao** [comment] 2023-08-11 09:54
> > > @aosolao delete three DB tables: `model`, `adapter` and `enforcer`, restart Casdoor
> > 
> > 
> > A new error
> > ```
> > [xorm] [warn]  2023/08/11 09:14:37.581033 Table provider has column custom_scope but struct has not related field
> > [xorm] [warn]  2023/08/11 09:14:37.635839 Table payment has column organization but struct has not related field
> > panic: Error 1146: Table 'casdoor.casbin_api_rule' doesn't exist
> > 
> > goroutine 1 [running]:
> > github.com/casdoor/casdoor/authz.InitApi()
> > 	/go/src/casdoor/authz/authz.go:111 +0x13f
> > main.main()
> > 	/go/src/casdoor/main.go:51 +0xaa
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @hsluoyz
> 
> What database you are using? The table will be created auto when Casdoor uses mysql.

I am using MySQL. As mentioned above, I deleted the three tables - model, adapter and enforcer - and then started casdoor with the new version, which led to the error I posted above.

**Comment by leo220yuyaodog** [comment] 2023-08-11 10:24
@aosolao Make sure the user connect database has permission to create table. If it is root user, what's version of your mysql? I can't reproduce your error on window and mysql 8.0

**Comment by aosolao** [comment] 2023-08-14 01:44
> @aosolao Make sure the user connect database has permission to create table. If it is root user, what's version of your mysql? I can't reproduce your error on window and mysql 8.0

The database I'm using is MySQL 5.7. I've successfully updated it to version 1.388 now. The mysql user permissions are not an issue. Last week when it failed, I could see that the database tables had already been created, but there was no data in the tables. But now it's resolved, there are no problems. Thank you.
