### ISSUE TITLE
[Bug]update owner error when update permission

### ISSUE THREAD

**Issue by shiningstarts** [casdoor/casdoor#3034] opened 2024-07-03 02:37 UTC
Update permission.owner and return Unaffected.
Version: v1.634.0
![image](https://github.com/casdoor/casdoor/assets/22713311/0050e846-466e-4f92-a788-7d0ff14fbe87)
![image](https://github.com/casdoor/casdoor/assets/22713311/0f0cf7e9-2944-4991-ac4b-0e99724062e3)

**Comment by SuccessZ** [comment] 2024-07-04 05:35
@shiningstarts Hi, I'm sorry that I can't reproduce your problem. I can only get "unaffected" when I click the Add button and then directly the Update button. Can you tell me the specific steps you took to trigger this bug?

**Comment by shiningstarts** [comment] 2024-07-04 06:56
> @shiningstarts Hi, I'm sorry that I can't reproduce your problem. I can only get "unaffected" when I click the Add button and then directly the Update button. Can you tell me the specific steps you took to trigger this bug?

In EditPage 
1. change owner and click save, return "Affected"
2. change owner and click save, return "Unaffected"

**Comment by hsluoyz** [comment] 2024-07-04 14:56
@shiningstarts I tested this and it worked: https://demo.casdoor.com/permissions/casbin/permission_deny_role

**Comment by SuccessZ** [comment] 2024-07-05 04:07
@shiningstarts The bug is probably that the frontend has not fully synchronized the updated status of the backend. 

In casdoor/web/src/PermissionEditPage.js:489, the frontend has not synchronized the backend's organizationName, and organizationName needs to be used to find the old permissions. 

In casdoor/object/permission.go:146, if the old permissions are not found, (ok, Unaffected) will be returned directly.

**Comment by SuccessZ** [comment] 2024-07-05 04:10
@shiningstarts This bug can be fixed by adding code organizationName: this.state.permission.owner to the function this.setState in casdoor/web/src/PermissionEditPage.js:489.

**Closed** 2024-07-06 03:24 UTC
Labels: bug
