### ISSUE TITLE
[Bug] An application should not be able to create users for other organizations

### ISSUE THREAD

**Issue by purefun** [casdoor/casdoor#3037] opened 2024-07-05 01:38 UTC
for `built-in` organization:
```sh
curl --location 'https://demo.casdoor.com/api/add-user' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic OGI0M2MyNDhiNjZmOTRjZmVhYmE6MDhiZGU1NGEzNTZhNGU4NTZkYmRjYzg4ZmQ0NDk3NDhhNmI0OGJhOQ==' \
--data '{
    "name": "charlie",
    "owner": "built-in"
}'
```

for `casbin` organization:
```sh
curl --location 'https://demo.casdoor.com/api/add-user' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic OGI0M2MyNDhiNjZmOTRjZmVhYmE6MDhiZGU1NGEzNTZhNGU4NTZkYmRjYzg4ZmQ0NDk3NDhhNmI0OGJhOQ==' \
--data '{
    "name": "charlie",
    "owner": "casbin"
}'
```

Both returned `{ "status": "ok"}`.

IMHO, it's unsafe for an api design. An application in casdoor can do anything almost, but its permissions should be limited within the organization.

**Comment by polarathene** [comment] 2024-07-06 06:49
duplicate of: https://github.com/casdoor/casdoor/issues/2887

**Closed** 2024-07-06 14:11 UTC
Labels: bug
